dist: trusty
sudo: required

git:
  submodules: false

addons:
  apt:
    packages:
    - sudo

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install git

# Do not use root to test the script
script:
    - sudo ./install.sh
    - echo -e "y\n" | ./prepare_all.sh
    - source ./install_command.sh
    - ./download.sh
    - ./guest-images/dev/microzed-image-1.2/build.sh

notifications:
  email: false
